name: Build CSV data

on:
  push:
    paths:
      - 'data/EdRegistry.csv'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm install -g csvtojson
      - run: csvtojson data/EdRegistry.csv > data/data.json

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/data.json
          git commit -m "Update data.json" || true
          git push
